In [37]:
#Задача 1

'''
import numpy as np
arr = np.random.uniform(0, 21, size = (4,7)).round(3)
min_val = arr.min()
max_val = arr.max()
x = arr
a = 1/(max_val-min_val)
b = -a * min_val
ans = a*x+b
ans
'''

array([[0.77560426, 0.00752765, 0.02847194, 0.87771405, 0.        ,
        0.44182712, 0.34852519],
       [0.87771405, 0.01049775, 0.27207087, 0.59611839, 0.40772224,
        0.7962925 , 0.86137853],
       [0.96261778, 0.33372593, 0.18424826, 0.82568619, 0.50798853,
        0.03190291, 0.78215895],
       [0.50081934, 0.2890721 , 1.        , 0.21374437, 0.53133961,
        0.00640107, 0.37520483]])

In [58]:
#задача 2
'''
import numpy as np
arr = np.random.randint(0, 11, (8,10))
index = np.argmin(np.sum(arr, axis = 1))
arr,arr[index]
'''

(array([[ 2,  0,  4,  5,  2,  4,  2, 10,  0,  8],
        [ 3,  3,  6,  2,  6,  8,  7,  4,  9,  8],
        [ 0,  9,  1,  1,  4,  0,  7,  4,  7,  6],
        [ 3,  1, 10,  3,  0,  5,  3,  3,  5, 10],
        [ 6,  3,  9,  4,  5,  7,  4,  1, 10,  8],
        [ 2,  0,  7,  7,  1, 10,  6,  7,  7,  7],
        [ 8,  1,  7,  8,  5,  3,  4,  7,  1, 10],
        [ 1,  3,  9,  3,  6,  0,  1,  9,  1,  9]]),
 array([ 2,  0,  4,  5,  2,  4,  2, 10,  0,  8]))

In [59]:
#Задача 3
'''
import numpy as np

vector1 = np.array([1, 2, 3, 4, 5])
vector2 = np.array([5, 4, 3, 2, 1])

ans = np.linalg.norm(vector1 - vector2)
ans
'''

Евклидово расстояние между вектором 1 и вектором 2: 6.324555320336759


In [72]:
#Задача 4
import numpy as np
A = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B=np.array([[3, -1], [2, 1]])
C=np.array([[7, 21], [11, 8], [8, 4]])
A_1 = np.linalg.inv(A)
B_1 = np.linalg.inv(B)
C_1 = -1*C
A_1 @ C_1 @ B_1

array([[ 1.00000000e+00,  1.11022302e-15],
       [-2.00000000e+00,  1.00000000e+00],
       [ 3.00000000e+00, -4.00000000e+00]])