Лабораторная работа №1
Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки numpy.

1. Файл minutes_n_ingredients.csv содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива numpy типа int32, используя np.loadtxt. Выведите на экран первые 5 строк массива.
2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.
3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля q0.75.
4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.
5. Посчитайте, сколько уникальных рецептов находится в датасете.
6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?
7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.
8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета
9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью
10. Выберите случайным образом и выведите информацию о 10 различных рецептах
11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.
12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.
13. Выведите процент "простых" рецептов в датасете
14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [59]:
import numpy as np
#1
data = np.loadtxt('minutes_n_ingredients.csv', delimiter=',', skiprows = 1, dtype=np.int32)
print(data[:5])


[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


In [60]:
#2
arr = data[:, 1:]
min_first = min(data[:,1])
min_second = min(data[:, 2])
max_first = max(data[:,1])
max_second = max(data[:, 2])
median_minutes = np.median(data[:, 1])
median_ingredients = np.median(data[:, 2])
mean_minutes = np.mean(data[:,1])
mean_ingredients = np.mean(data[:, 2])
print(mean_minutes, mean_ingredients)
print([min_first, min_second])
print([max_first, max_second])
print(median_minutes, median_ingredients)


21601.00169 9.05528
[0, 1]
[2147483647, 39]
40.0 9.0


In [61]:
#3
quantile_value = np.quantile(data[:, 1], 0.75)
print(quantile_value)
data[:, 1] = np.minimum(data[:, 1], quantile_value)

65.0


In [62]:
#4
counter = np.count_nonzero(data[:, 1] == 0)
counter

479

In [63]:
#5
data[:, 1] = np.where(data[:, 1] == 0, 1, data[:, 1])

In [64]:
#6
counter_unique_id = len(np.unique(data[:,1]))
counter_unique_id

65

In [65]:
#7
ans_7 = data[data[:, 2] <= 5]
ans_7

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]])

In [66]:
#8
count_recipes = data[:, 2] / data[:, 1]
ans_8 = np.max(data[:, 2] / data[:, 1])
ans_8, count_recipes

(24.0,
 array([0.26666667, 0.28      , 0.6       , ..., 0.23076923, 0.8       ,
        0.21538462]))

In [67]:
#9
ans_9 = data[data[:, 1].argsort()][::-1]
answer_9 = np.mean(ans_9[:100, 2])
answer_9



9.96

In [68]:
#10
import random
ans_10 = random.choices(data, k = 10, )
ans_10

[array([350040,     10,      5]),
 array([235732,     15,      8]),
 array([225202,     25,      8]),
 array([275888,     55,     13]),
 array([3037,    1,   16]),
 array([220579,     35,      9]),
 array([283186,     10,      4]),
 array([368276,     10,      7]),
 array([214012,     65,     12]),
 array([466871,     30,      8])]

In [74]:
#11

average_11 = np.mean(data[:,2] < np.mean(data[:, 2]))*100
average_11



58.802

In [87]:
#12
simple_recipe = (data[:, 1] <= 20) & (data[:, 2] <= 5)
data = np.column_stack((data, simple_recipe))
print(data)



[[127244     60     16      0      0      0      0]
 [ 23891     25      7      0      0      0      0]
 [ 94746     10      6      0      0      0      0]
 [ 67660      5      6      0      0      0      0]
 [157911     60     14      0      0      0      0]]


In [92]:
#13

average_13 = np.mean(data[:, 3])*100
average_13



9.552